name: lxqt-organizer-snap
base: core18
title: LXQt-Organizer-snap (unofficial)
summary: Personal Information Manager
description: |
  LXQt Organizer is a lightweight organizer for personal information management.  
  This is the unofficial snap packaging.  
  Upstream: https://github.com/lxqt/lxqt-organizer  

grade: stable
confinement: strict

adopt-info: lxqt-organizer-snap
apps:
  lxqt-organizer-snap:
    adapter: full
    command: usr/bin/lxqt-organizer
    command-chain:
      - bin/desktop-launch
    environment:
      QT_STYLE_OVERRIDE: Fusion
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    desktop: usr/share/applications/lxqt-organizer.desktop
    plugs:
      - unity7
      - x11
      - wayland
      - opengl
      - desktop
      - desktop-legacy
      - home

parts:
  lxqt-organizer-snap:
    source: https://github.com/lxqt/lxqt-organizer.git
    source-type: git
    source-branch: master
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
    after:
      - desktop-qt5
    override-pull: |
      snapcraftctl pull
      c1=`git log --oneline -n 1`
      cd $SNAPCRAFT_PROJECT_DIR
      c2=`git log --oneline -n 1`
      d=`date +%y%m%d`
      { t1=${c1#???}; c1=${c1%$t1}; }
      { t2=${c2#???}; c2=${c2%$t2}; }
      ver="$d.$SNAP_ARCH-$c1.$c2"
      echo "Set version: $ver"
      snapcraftctl set-version $ver
#
    build-snaps:
      - lxqt-build-tools-snap/latest/edge
      - libqtxdg-snap/latest/edge
    build-packages:
      - g++
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5widgets5
      - libkf5windowsystem-dev
      - libqt5svg5-dev
      - libqt5x11extras5-dev
      - libx11-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libqt5sql5

    override-stage: |
      snapcraftctl stage
      sed -e '/^Name/s/$/ - snap/' -i usr/share/applications/lxqt-organizer.desktop
#
    stage-snaps:
      - liblxqt-snap/latest/edge
    stage-packages:
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5svg5
      - libqt5widgets5
      - libqt5x11extras5
      - libx11-6
      - libqt5sql5-sqlite
      #- qttranslations5-l10n
      - fcitx-frontend-qt5

  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libgtk2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all
