name: lxqt-organizer-snap
base: core18
title: LXQt-Organizer-snap (unofficial)
summary: Personal Information Manager
description: |
  LXQt Organizer is a lightweight organizer for personal information management.  
  This is the unofficial snap packaging.  
  Upstream: https://github.com/lxqt/lxqt-organizer  

grade: stable
confinement: strict

adopt-info: lxqt-organizer-snap
apps:
  lxqt-organizer-snap:
    adapter: full
    command: usr/bin/organizer
    command-chain:
      - bin/desktop-launch
    environment:
      QT_STYLE_OVERRIDE: Fusion
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    desktop: usr/share/applications/organizer.desktop
    plugs:
      - unity7
      - x11
      - wayland
      - opengl
      - desktop
      - desktop-legacy
      - home

parts:
  lxqt-organizer-snap:
    source: https://github.com/lxqt/lxqt-organizer.git
    source-type: git
    source-branch: master
    plugin: cmake
    configflags:
      - -DCMAKE_FIND_ROOT_PATH=$SNAPCRAFT_STAGE
      - -DCMAKE_INSTALL_PREFIX=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current/usr: usr
    after:
      - desktop-qt5
      - liblxqt
    override-pull: |
      snapcraftctl pull
      c1=`git log --oneline -n 1`
      cd $SNAPCRAFT_PROJECT_DIR
      c2=`git log --oneline -n 1`
      d=`date +%y%m%d`
      { t1=${c1#???}; c1=${c1%$t1}; }
      { t2=${c2#???}; c2=${c2%$t2}; }
      ver="$d.$SNAP_ARCH-$c1.$c2"
      echo "Set version: $ver"
      snapcraftctl set-version $ver
#
    build-snaps:
      - lxqt-build-tools-snap/latest/edge
    build-packages:
      - g++
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5widgets5
      - libkf5windowsystem-dev
      - libqt5svg5-dev
      - libqt5x11extras5-dev
      - libx11-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libqt5sql5

    override-stage: |
      snapcraftctl stage
      sed -e '/^Name/s/$/ - snap/' -i usr/share/applications/*.desktop
#
    stage-packages:
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5svg5
      - libqt5widgets5
      - libqt5x11extras5
      - libx11-6
      - libqt5sql5-sqlite
      #- qttranslations5-l10n
      - fcitx-frontend-qt5

  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libgtk2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all

  liblxqt:
    source: https://github.com/lxqt/liblxqt.git
    source-type: git
    plugin: cmake
    configflags:
      - -DCMAKE_FIND_ROOT_PATH=$SNAPCRAFT_STAGE
      - -DCMAKE_INSTALL_PREFIX=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current/usr: usr

    after:
      - libqtxdg
    build-snaps:
      - lxqt-build-tools-snap/latest/edge
    build-packages:
      - g++
      - libqt5widgets5
      - libqt5dbus5
      - qttools5-dev
      - libkf5windowsystem-dev
      - libpolkit-qt5-1-dev
      - libqt5x11extras5-dev
      - libx11-dev
      - libxss-dev
      - libqt5svg5-dev
      - libqt5xdgiconloader-dev
      - libglib2.0-dev
    stage-packages:
      - qttranslations5-l10n
      - libqt5xdg-dev
      - libqt5xdgiconloader-dev
      - desktop-file-utils
      - shared-mime-info
      - libkf5windowsystem5
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5widgets5
      - libqt5x11extras5
      - libqt5xdg3
      - libstdc++6
      - libx11-6
      - libxss1
    stage:
      - -usr/include/qt5xdg/xdgaction.h
      - -usr/include/qt5xdg/xdgautostart.h
      - -usr/include/qt5xdg/xdgdesktopfile.h
      - -usr/include/qt5xdg/xdgdirs.h
      - -usr/include/qt5xdg/xdgicon.h
      - -usr/include/qt5xdg/xdgmacros.h
      - -usr/include/qt5xdg/xdgmenu.h
      - -usr/include/qt5xdg/xdgmenuwidget.h
      - -usr/include/qt5xdg/xdgmimetype.h
      - -usr/include/qt5xdg/xmlhelper.h
      - -usr/lib/i386-linux-gnu/qt5/plugins/iconengines/libQt5XdgIconPlugin.so
      - -usr/share/cmake/qt5xdg/qt5xdg-config-version.cmake
      - -usr/share/cmake/qt5xdg/qt5xdg-config.cmake
      - -usr/share/cmake/qt5xdg/qt5xdg-targets.cmake
      - -usr/share/cmake/qt5xdgiconloader/qt5xdgiconloader-config-version.cmake
      - -usr/share/cmake/qt5xdgiconloader/qt5xdgiconloader-targets.cmake

  libqtxdg:
    source: https://github.com/lxqt/libqtxdg.git
    source-type: git
    plugin: cmake
    configflags:
      - -DCMAKE_FIND_ROOT_PATH=$SNAPCRAFT_STAGE
      - -DCMAKE_INSTALL_PREFIX=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current/usr: usr

    build-snaps:
      - lxqt-build-tools-snap/latest/edge
    build-packages:
      - g++
      - libmagic-dev
      - libqt5svg5-dev
      - pkg-config
      - qtbase5-private-dev
      - qttools5-dev
      - qttools5-dev-tools
    stage-packages:
      - libfile-mimeinfo-perl
      - shared-mime-info
      - file
      - libglib2.0-bin
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5widgets5
      - libqt5xml5
      - libstdc++6
      - try: [gtk-update-icon-cache]
      - libmagic1
      - qttranslations5-l10n
